---
# Playbook to deploy Ghost and its components
- name: Deploy Ghost
  hosts: localhost
  gather_facts: false
  roles:
    - gke_ckeck_first_deploy
    - gke_deploy_db
    - gke_deploy_ghost
    - gke_deploy_dashboards
    - gke_first_deploy
