---
# Playbook to undeploy Ghost and its components
- name: Undeploy Ghost
  hosts: localhost
  gather_facts: false
  roles:
    - gke_first_undeploy
    - gke_undeploy_ghost
    - gke_undeploy_db
    - gke_undeploy_dashboards
  