---
- name: Create namespace for Ghost application
  k8s:
    api_version: v1
    kind: Namespace
    name: ghost
    state: present

- name: Deploy ghost application.
  k8s:
    api_version: apps/v1
    kind: Deployment
    name: ghost
    namespace: ghost
    state: present
    container:
      - name: ghost
        image: ghost:5.14.1
        ports:
          - containerPort: 2368

- name: Create Service for Ghost application
  k8s:
    api_version: v1
    kind: Service
    name: ghost
    namespace: ghost
    state: present
    spec:
      selector:
        app: ghost
      ports:
        - port: 80
          target_port: 2368
