---
- name: Create a namespace for the MySQL deployment
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: '{{db_namespace}}'

- name: Deploy MySQL on the cluster
  kubernetes.core.k8s:
    state: present
    definition:
      metadata:
        name: '{{db_deploy_name}}'
        namespace: '{{db_namespace}}'
      api_version: v1
      kind: Deployment
      spec:
        selector:
          matchLabels:
            app: '{{ app }}'
        strategy:
          type: Recreate
        template:
          metadata:
            labels:
              app: '{{ app }}'
          spec:
            containers:
              - name: '{{ app }}'
                image: '{{ image }}'
                ports:
                  - containerPort: '{{ db_port }}'
                env:
                  - name: MYSQL_ROOT_PASSWORD
                    value: '{{ mysql_root_password }}'
                  - name: MYSQL_DATABASE
                    value: '{{ app_db_name }}'
                  - name: MYSQL_USER
                    value: '{{ app_db_user }}'
                  - name: MYSQL_PASSWORD
                    value: '{{ app_db_pass }}' # Use Secret object in real usage
                volumeMounts:
                  - name: mysql-persistent-storage
                    mountPath: /var/lib/mysql
            volumes:
              - name: mysql-persistent-storage
                persistentVolumeClaim:
                  claimName: '{{ db_pvc_name }}'

- name: Create a persistent volume claim for the MySQL deployment
  kubernetes.core.k8s:
    state: present
    definition:
      metadata:
        name: '{{ db_pvc_name }}'
        namespace: '{{db_namespace}}'
      api_version: v1
      kind: PersistentVolumeClaim
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: 10Gi

- name: Create a service for the MySQL deployment
  kubernetes.core.k8s:
    state: present
    definition:
      api_version: v1
      kind: Service
      metadata:
        name: '{{ db_service_name }}'
        namespace: '{{ db_namespace }}'
      spec:
        type: LoadBalancer
        selector:
          app: '{{ app }}'
        ports:
          - port: '{{ db_port }}'
            targetPort: '{{ db_port }}'
