- name: Undeploy Database Deployment
  shell: kubectl delete deployment '{{db_deploy_name}}' -n '{{db_namespace}}'

- name: Remove Persistent Volume on Database Deployment
  shell: kubectl delete pvc '{{db_pvc_name}}' -n '{{db_namespace}}'
  when: remome_db_volume == "true"